### ISSUE TITLE
Very minor spelling fixes.

### ISSUE THREAD

**Issue by 12edge** [ralsina/boxes-book#1]
A wonderful book. I have been wondering about learning and using Git.
Two very minor spelling errors or typos in the section on GIT: 
1) Right before the heading "Rebase": "Ofthen" should be "Often".
2) Soon after the same heading "Rebase": "casses" should be "causes".

I had never heard of the font or hyphenation packages. Thank you. I've just used svgwrite for fun drawing.

**Comment by ralsina** [comment]
Thanks for the feedback!

I will fix the typos ASAP

**Comment by ralsina** [comment]
Pushed, it will appear in the site soon.
